services:
  - type: web
    name: my-laravel-app
    env: php
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y curl && curl -sL https://deb.nodesource.com/setup_14.x | bash -
      apt-get install -y nodejs
      npm install
      npm run build
      composer install --no-dev --optimize-autoloader
      php artisan migrate --force
    startCommand: |
      php artisan serve --host 0.0.0.0 --port 10000
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:zLzOaLWwv5/N9FxBvNU/5EAEh6NxamOFCBfIwdAKylI=
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://tu-dominio-en-render.com  # Reemplaza con la URL que Render te proporcione

      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: your-render-db-host  # Reemplaza con el host de la base de datos en Render
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: MiniShopDB
      - key: DB_USERNAME
        value: your-db-username  # Reemplaza con el usuario de la base de datos
      - key: DB_PASSWORD
        value: your-db-password  # Reemplaza con la contraseña de la base de datos

      - key: LOG_CHANNEL
        value: stack
      - key: LOG_DEPRECATIONS_CHANNEL
        value: null
      - key: LOG_LEVEL
        value: debug

      - key: BROADCAST_DRIVER
        value: log
      - key: CACHE_DRIVER
        value: file
      - key: FILESYSTEM_DISK
        value: local
      - key: QUEUE_CONNECTION
        value: sync
      - key: SESSION_DRIVER
        value: file
      - key: SESSION_LIFETIME
        value: 120

      - key: MEMCACHED_HOST
        value: 127.0.0.1

      - key: REDIS_HOST
        value: 127.0.0.1
      - key: REDIS_PASSWORD
        value: null
      - key: REDIS_PORT
        value: 6379

      - key: MAIL_MAILER
        value: smtp
      - key: MAIL_HOST
        value: mailpit
      - key: MAIL_PORT
        value: 1025
      - key: MAIL_USERNAME
        value: null
      - key: MAIL_PASSWORD
        value: null
      - key: MAIL_ENCRYPTION
        value: null
      - key: MAIL_FROM_ADDRESS
        value: "hello@example.com"
      - key: MAIL_FROM_NAME
        value: "Laravel"

      - key: AWS_ACCESS_KEY_ID
        value: ""
      - key: AWS_SECRET_ACCESS_KEY
        value: ""
      - key: AWS_DEFAULT_REGION
        value: us-east-1
      - key: AWS_BUCKET
        value: ""
      - key: AWS_USE_PATH_STYLE_ENDPOINT
        value: false

      - key: PUSHER_APP_ID
        value: ""
      - key: PUSHER_APP_KEY
        value: ""
      - key: PUSHER_APP_SECRET
        value: ""
      - key: PUSHER_HOST
        value: ""
      - key: PUSHER_PORT
        value: 443
      - key: PUSHER_SCHEME
        value: https
      - key: PUSHER_APP_CLUSTER
        value: mt1

      - key: VITE_APP_NAME
        value: "Laravel"
      - key: VITE_PUSHER_APP_KEY
        value: ""
      - key: VITE_PUSHER_HOST
        value: ""
      - key: VITE_PUSHER_PORT
        value: ""
      - key: VITE_PUSHER_SCHEME
        value: https
      - key: VITE_PUSHER_APP_CLUSTER
        value: mt1
    build:
      docker:
        base: php:8.0-apache
    env:
      - node
